#
#
# Copyright Â© 2020-2022 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#      http://www.apache.org/licenses/LICENSE-2.0
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
#

name: csi-powerstore
apiVersion: v2
version: 2.5.0
appVersion: "2.5.0"
kubeVersion: ">= 1.21.0 < 1.26.0"
#If you are using a complex K8s version like "v1.22.3-mirantis-1", use this kubeVersion check instead
#WARNING: this version of the check will allow the use of alpha and beta versions, which is NOT SUPPORTED
#kubeVersion: ">= 1.21.0-0 < 1.26.0-0"
description: |
  PowerStore CSI (Container Storage Interface) driver Kubernetes
  integration. This chart includes everything required to provision via CSI as
  well as a PowerStore StorageClass.
keywords:
- csi
- storage
home: https://github.com/dell/csi-powerstore
sources:
- https://github.com/dell/csi-powerstore
maintainers:
- name: DellEMC
