## K8S/DRIVER ATTRIBUTES
########################

# driverName: defines the name of driver
# Allowed values: string
# Default value: None
driverName: "csi-powerstore.dellemc.com"

# Specify kubelet config dir path.
# Ensure that the config.yaml file is present at this path.
# Default value: None
kubeletConfigDir: /var/lib/kubelet

# nodeFCPortsFilterFile: It is the name of the environment variable which store path to the file which
# provide list of WWPN which should be used by the driver for FC connection on this node
# If file not exist or empty or in invalid format, then the driver will use all available FC ports
# Allowed Values: string
# Default Value: None
# Example:
# content of the file:
#   21:00:00:29:ff:48:9f:6e,21:00:00:29:ff:48:9f:6e
nodeFCPortsFilterFile: /etc/fc-ports-filter

# externalAccess: allows to specify additional entries for hostAccess of NFS volumes. Both single IP address and subnet are valid entries.
# Allowed Values: x.x.x.x/xx or x.x.x.x
# Default Value: None
externalAccess:

# imagePullPolicy: Policy to determine if the image should be pulled prior to starting the container.
# Allowed values:
#  Always: Always pull the image.
#  IfNotPresent: Only pull the image if it does not already exist on the node.
#  Never: Never pull the image.
# Default value: None
imagePullPolicy: IfNotPresent

# healthMonitorInterval: Interval of monitoring volume health condition
# Allowed values: Number followed by unit (s,m,h)
# Examples: 60s, 5m, 1h
# Default value: None
# Default value: 60s
volumeHealthMonitorInterval: 60s

# controller: configure controller specific parameters
controller:
  # controllerCount: defines the number of csi-powerscale controller pods to deploy to
  # the Kubernetes release.
  # Allowed values: n, where n > 0
  # Default value: None
  controllerCount: 2

  # volumeNamePrefix: defines a string prepended to each volume created by the CSI driver.
  # Allowed values: string
  # Default value: None
  volumeNamePrefix: csivol

  # snapshot: allows to enable/disable snapshot feature
  snapshot:
    # enabled: Enable/Disable volume snapshot feature
    # Allowed values:
    #   true: enable volume snapshot feature(install snapshotter sidecar)
    #   false: disable volume snapshot feature(do not install snapshotter sidecar)
    # Default value: None
    enabled: true

    # snapNamePrefix: Prefix to apply to the names of a created snapshots
    # Allowed values: string
    # Default value: None
    snapNamePrefix: csisnap

  # resizer: allows to enable/disable resizer feature
  resizer:
    # enabled: Enable/Disable volume expansion feature
    # Allowed values:
    #   true: enable volume expansion feature(install resizer sidecar)
    #   false: disable volume expansion feature(do not install resizer sidecar)
    # Default value: None
    enabled: true

  # replication: allows to configure replication
  # Replication CRDs must be installed before installing driver
  replication:
    # enabled: Enable/Disable replication feature
    # Allowed values:
    #   true: enable replication feature(install dell-csi-replicator sidecar)
    #   false: disable replication feature(do not install dell-csi-replicator sidecar)
    # Default value: false
    enabled: false

    # image: Image to use for dell-csi-replicator. This shouldn't be changed
    # Allowed values: string
    # Default value: None
    image: dellemc/dell-csi-replicator:v1.0.0

    # replicationContextPrefix: prefix to use for naming of resources created by replication feature
    # Allowed values: string
    # Default value: powerstore
    replicationContextPrefix: "powerstore"

    # replicationPrefix: prefix to prepend to storage classes parameters
    # Allowed values: string
    # Default value: replication.storage.dell.com
    replicationPrefix: "replication.storage.dell.com"

  # nodeSelector: Define node selection constraints for controller pods.
  # For the pod to be eligible to run on a node, the node must have each
  # of the indicated key-value pairs as labels.
  # Leave as blank to consider all nodes
  # Allowed values: map of key-value pairs
  # Default value: None
  # Examples:
  #   node-role.kubernetes.io/master: ""
  nodeSelector:
  #   node-role.kubernetes.io/master: ""

  # tolerations: Define tolerations for the controllers, if required.
  # Leave as blank to install controller on worker nodes
  # Default value: None
  tolerations:
  #  - key: "node-role.kubernetes.io/master"
  #    operator: "Exists"
  #    effect: "NoSchedule"

# node: configure node pod specific parameters
node:
  # nodeNamePrefix: defines a string prepended to each node registered by the CSI driver.
  # Allowed values: string
  # Default value: None
  nodeNamePrefix: csi-node

  # nodeIDPath: defines the path to file with node identifier (e.g. /etc/machine-id, /etc/hostname).
  # Allowed values: string
  # Default value: None
  nodeIDPath: /etc/machine-id

  # nodeSelector: Define node selection constraints for node pods.
  # For the pod to be eligible to run on a node, the node must have each
  # of the indicated key-value pairs as labels.
  # Leave as blank to consider all nodes
  # Allowed values: map of key-value pairs
  # Default value: None
  # Examples:
  #   node-role.kubernetes.io/master: ""
  nodeSelector:
  #   node-role.kubernetes.io/master: ""

  # tolerations: Define tolerations for the node pods, if required.
  # Leave as blank to consider all worker nodes
  # Default value: None
  tolerations:
  #  - key: "node-role.kubernetes.io/master"
  #    operator: "Exists"
  #    effect: "NoSchedule"

## PLATFORM ATTRIBUTES
######################

# connection: allows to configure connection to storage array
connection:
  # connection.enableCHAP: allows to enable CHAP for iSCSI connections
  # CHAP password will be autogenerated by driver
  # Allowed values:
  #   true : enable CHAP
  #   false: disable CHAP
  # Default value: false
  enableCHAP: false

# CSI driver log level
# Allowed values: "error", "warn"/"warning", "info", "debug", "error"
# Default value: "debug"
logLevel: "debug"

# CSI driver log format
# Allowed values: "TEXT" or "JSON"
# Default value: "JSON"
logFormat: "JSON"
