apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ .Values.driverName }}
spec:
  storageCapacity: true
  podInfoOnMount: true
  fsGroupPolicy: {{ .Values.fsGroupPolicy }}
  volumeLifecycleModes:
  - Persistent
  - Ephemeral
