apiVersion: v1
kind: Secret
metadata:
  name: powerstore-creds
  # Set driver namespace
  namespace: csi-powerstore
type: Opaque
data:
  # set username to the base64 encoded username
  username:
  # set password to the base64 encoded password
  password:
